# Generated by Django 4.0.4 on 2022-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invEStiGuideAPI', '0002_alter_issuer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='image_url',
            field=models.TextField(),
        ),
    ]
