# Generated by Django 4.0.4 on 2022-06-13 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ESG_Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('esg_rating', models.IntegerField()),
                ('asset_rating', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('is_index', models.BooleanField()),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invEStiGuideAPI.assetclass')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invEStiGuideAPI.country')),
                ('esg_concern', models.ManyToManyField(related_name='fund', to='invEStiGuideAPI.esg_concern')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invEStiGuideAPI.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=200)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invEStiGuideAPI.fund')),
                ('recommendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_for_me', to=settings.AUTH_USER_MODEL)),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_rec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invEStiGuideAPI.country')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invEStiGuideAPI.industry'),
        ),
        migrations.AddField(
            model_name='fund',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invEStiGuideAPI.issuer'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='invEStiGuideAPI.issuer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
