# Generated by Django 4.0.4 on 2022-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invEStiGuideAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='image_url',
            field=models.TextField(),
        ),
    ]
